version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the project directory inside the container
      - ..:/workspace:cached
    
    # Overrides default command so container doesn't shut down immediately
    command: sleep infinity

    # Connect to the MongoDB database service container
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
